"""Added profile table

Revision ID: 3da06a61a2b1
Revises: 
Create Date: 2022-02-22 20:55:37.226947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3da06a61a2b1"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("sex", sa.SmallInteger(), nullable=False),
        sa.Column(
            "number_of_purchases",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=True,
        ),
        sa.Column("avg_price_of_cart", sa.Integer(), nullable=True),
        sa.Column("days_since_last_purchase", sa.SmallInteger(), nullable=True),
        sa.Column("last_purchase_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("average_days_beetween_purchases", sa.SmallInteger(), nullable=True),
        sa.Column("average_number_of_purchases", sa.Integer(), nullable=True),
        sa.Column("device_list", sa.ARRAY(sa.String(length=10)), nullable=True),
        sa.Column("locations_list", sa.ARRAY(sa.String(length=100)), nullable=True),
        sa.Column("last_seen_location", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profile")
    # ### end Alembic commands ###
