---

docker_user: "{{ vault_docker_user }}"
docker_token: "{{ vault_docker_token }}"
postgres_host: "{{ vault_postgres_host }}"
postgres_port: 5432
postgres_password: "{{ vault_postgres_password }}"
postgres_user: "{{ vault_postgres_user }}"
postgres_db: "{{ vault_postgres_db }}"
le_email: "{{ vault_le_email }}"
le_domain: "{{ vault_le_domain }}"
