---
services:
  app:
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile.dev
    image: profile-app-dev
    command: python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./../:/app/mount:ro
    env_file:
      - ./../.env.example
    environment:
      - POSTGRES_HOST=db
      - DEBUG=1
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./../.env.example
    ports:
      - "5432:5432"

volumes:
  postgres_data:
