---
services:
  app:
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    image: profile-app
    env_file:
      - ./../.env.example
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./../.env.example

  nginx:
    image: nginx:1-alpine
    volumes:
      - ./../etc/nginx/templates:/etc/nginx/templates
    ports:
      - "8000:80"
    depends_on:
      - app

volumes:
  postgres_data:
